name: example
description: A project used to demo the Todo Reporter
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.4.0'

dependencies:
  finject_flutter: ^0.3.2

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  finject_generator: ^0.3.3


dependency_overrides:
  finject_generator:
    path: ../finject_generator
  finject_flutter:
    path: ../finject_flutter
  finject:
    path: ../finject