name: example
description: A project used to demo the Todo Reporter
version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  finject_flutter: ^0.1.4

dev_dependencies:
  build_runner: 1.7.2
  flutter_test:
    sdk: flutter
  finject_generator: ^0.1.8

dependency_overrides:
  finject_flutter:
    path: ../finject_flutter
  finject_generator:
    path: ../finject_generator
  finject:
    path: ../finject