name: example
description: A project used to demo the Todo Reporter
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  finject_flutter:
    path: ../finject_flutter/


dev_dependencies:
  build_runner: 1.7.2
  flutter_test:
    sdk: flutter
  finject_generator:
    path: ../finject_generator/

