language: dart
dart: stable
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH=$PATH:$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin
  - flutter doctor
script:
  - tool/ci_analize
cache:
  directories:
    - $HOME/.pub-cache
