language: dart
dart: stable
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH=$PATH:$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin
  - flutter doctor
script:
  - tool/ci_analize
  - if [ $FLUTTER_CHANNEL = "stable" ]; then
    bash <(curl -s https://codecov.io/bash);
    fi
cache:
  directories:
    - $HOME/.pub-cache
