// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'annotations_test.dart' as annotations_test;
import 'qualifier_factory_test.dart' as qualifier_factory_test;
import 'qualifiers_test.dart' as qualifiers_test;
import 'scope_test.dart' as scope_test;

void main() {
  annotations_test.main();
  qualifiers_test.main();
  qualifier_factory_test.main();
  scope_test.main();
}
