name: finject_generator
description: Dart code generator for dependency injection finject library. Inspired with SpringFramework, Dagger2, and Angular DI solution
version: 0.3.3
homepage: https://github.com/TomMannson/Finject

environment:
  sdk: '>=2.3.0 <3.5.0'

dependencies:
  collection: ^1.14.13
  analyzer: '>=4.4.0 <6.0.0'
  build: '>=2.1.0 <2.4.0'
  source_gen: ^1.2.6
  finject: ^0.3.2
  code_builder: ^4.2.0
  path: ^1.8.2
  glob: ^2.1.1
  type_token: ^1.0.4
  xfile: ^1.1.0
  
dev_dependencies:
  lints: any
  build_test: ^2.1.5
  build_runner: 2.3.2
  test: ^1.22.0
  mockito: ^5.3.2
  logging: ^1.1.0
#  test_coverage: ^0.5.0
