name: finject_generator
description: Dart code generator for dependency injection finject library. Inspired with SpringFramework, Dagger2, and Angular DI solution
version: 0.3.0
homepage: https://github.com/TomMannson/Finject

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  analyzer: ^0.39.4
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  finject: ^0.3.0
  dartpoet: ^1.0.6+3
  path: ^1.6.4
  glob: ^1.2.0
  
dev_dependencies:
  pedantic: ^1.0.0
  build_test: ^0.10.0
  build_runner: 1.7.2
  test: ^1.0.0
  mockito: ^4.1.1
  logging: ^0.11.0
  test_coverage: ^0.4.0
