#!/bin/bash --
# Copyright (c) 2016, Google Inc. Please see the AUTHORS file for details.
# All rights reserved. Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

set -e

directories="finject finject_generator finject_flutter"

parent_directory=$PWD

for directory in $directories; do
  echo
  echo "*** Formatting $directory..."
  echo
  cd "$parent_directory/$directory"

  dartfmt -w $(find bin lib test -name \*.dart 2>/dev/null)
done

for directory in $directories; do
  echo
  echo "*** Building $directory..."
  echo
  cd "$parent_directory/$directory"

  rm example -r

  ../flutter/bin/flutter pub get
  ../flutter/bin/flutter pub upgrade

  # Clear any pre-existing build output so package:build doesn't get confused
  # when we use built_value to build itself.
  rm -rf .dart_tool/build/

  grep -q build_runner pubspec.yaml && \
      ../flutter/bin/flutter pub run build_runner build \
          --delete-conflicting-outputs \
          --fail-on-severe
done

for directory in $directories; do
  echo
  echo "*** Analyzing $directory..."
  echo
  cd "$parent_directory/$directory"

  dartanalyzer \
      --fatal-warnings \
      --fatal-infos \
      --packages="$PWD/.packages" \
      $(find bin lib test -name \*.dart 2>/dev/null)
done



for directory in $directories; do
  echo
  echo "*** Testing $directory..."
  echo
  cd "$parent_directory/$directory"

  ../flutter/bin/flutter pub run test
done

branch_name="$(git rev-parse --abbrev-ref HEAD)"


if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$branch_name" == "master" ]
then

	dart_directories="finject finject_generator"
	flutter_directories="finject_flutter"
  
	for directory in $dart_directories; do
	  echo
	  echo "*** Test coverage $directory..."
	  echo
	  cd "$parent_directory/$directory"

	  pub run test_coverage
	done

	for directory in $flutter_directories; do
	  echo
	  echo "*** Test coverage $directory..."
	  echo
	  cd "$parent_directory/$directory"

	  ../flutter/bin/flutter test --coverage
	done

	cd $parent_directory

	bash <(curl -s https://codecov.io/bash)
fi
