name: finject
description: Package contains required annotations and classes for DI definition.
version: 0.2.0
homepage: https://github.com/TomMannson/Finject

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  test: 1.3.4
  pedantic: ^1.0.0